package com.seppia.action;

import java.util.ArrayList;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;

import com.google.gson.*;
import com.google.maps.*;
import com.seppia.util.Utility;
import com.seppia.model.*;
import com.seppia.dao.*;

public class LocationFetcher {
	
	public Location transferLocationFechted(LocationFetched fetchedLocation){
		Location location = new Location();
		return location;
	}
	
	public LocationFetched transferJSONtoLocationFetched(String jsonResult){
		LocationFetched location = new LocationFetched(jsonResult);
		return location;
	}
	
	public String saveRawJsonResult(String jsonResult){
		//save json string as 1000 refresh result per file on disk
		//approx. 100k per file if full
		return "";
	}
	
	public String addLocationToLocationTable(Location location){
		//call location db function, just a wrapper
		//indicate auto creation by adding column boolean isAutoGenerated
		return"";
	}
}
